# drone state
STATE_ALIVE = 0
STATE_DEAD = 1

# what it is doing now
ACTION_WELCOME = -1
ACTION_INITIAL_SEARCHING = 0x00
ACTION_TRACKING = 0x01
ACTION_GOINGTOZONE = 0x10
ACTION_CHARGING = 0x100
ACTION_ENTITY_SEARCHING = 0x1000
ACTION_TURNING = 0x10000

# program phase
PHASE_SETTING = 0
PHASE_UPDATE = 1

# initialsearch way
INIT_START_NEAREST = 0
INIT_START_FARTHEST = 1
INIT_START_SMALLEST = 2
INIT_START_LARGEST = 3

# Command_ID
CMD_DRONE_HEADING_ALT = 11
CMD_GIMBAL_SCAN = 21
CMD_GIMBAL_SET = 22

# hazardzonetype
ZONE_FIRE = 1
ZONE_SMOKE = 2
ZONE_NONE = 0